name: math_facts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  provider: ^6.1.5+1
  logger: ^2.6.2
  typewritertext: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/math_facts.json
    - assets/images/
  
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  image_path: "assets/app_logo_square.png"
  web:
    generate: true
    image_path: "assets/app_logo_square.png"